CREATE TABLE IF NOT EXISTS SPRING_AI_CHAT_MEMORY (
  conversation_id VARCHAR(100) NOT NULL,
  content LONGTEXT NOT NULL,
  type ENUM('USER', 'ASSISTANT', 'SYSTEM', 'TOOL') NOT NULL,
  timestamp TIMESTAMP(6) NOT NULL,
  INDEX SPRING_AI_CHAT_MEMORY_CONVERSATION_ID_TIMESTAMP_IDX (conversation_id, timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
